// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI7KeZ2jBmMmXLUnjg20banPx_QyjlPKU',
    appId: '1:122872682348:web:c7b65b6499377a131c0549',
    messagingSenderId: '122872682348',
    projectId: 'html-e60cc',
    authDomain: 'html-e60cc.firebaseapp.com',
    storageBucket: 'html-e60cc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8nX5Ur6iDkC8fSP3gn_8L-hZwxMgMNI',
    appId: '1:122872682348:android:3a3c1784e79f8d971c0549',
    messagingSenderId: '122872682348',
    projectId: 'html-e60cc',
    storageBucket: 'html-e60cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc6uKSHBnY6pIVPfTETBtB2-aI7ddFQtw',
    appId: '1:122872682348:ios:5622e369df76889b1c0549',
    messagingSenderId: '122872682348',
    projectId: 'html-e60cc',
    storageBucket: 'html-e60cc.firebasestorage.app',
    iosBundleId: 'com.example.timeKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc6uKSHBnY6pIVPfTETBtB2-aI7ddFQtw',
    appId: '1:122872682348:ios:5622e369df76889b1c0549',
    messagingSenderId: '122872682348',
    projectId: 'html-e60cc',
    storageBucket: 'html-e60cc.firebasestorage.app',
    iosBundleId: 'com.example.timeKeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI7KeZ2jBmMmXLUnjg20banPx_QyjlPKU',
    appId: '1:122872682348:web:1abbff08fbe294f21c0549',
    messagingSenderId: '122872682348',
    projectId: 'html-e60cc',
    authDomain: 'html-e60cc.firebaseapp.com',
    storageBucket: 'html-e60cc.firebasestorage.app',
  );
}
